 
package swingserver;
import java.io.*;
import java.net.*;
import java.awt.Toolkit;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import java.sql.*;
import javax.swing.ImageIcon;
 
public class FishValue extends javax.swing.JFrame {

    Toolkit toolkit;
   Timer timer;
     Connection con;
       int deviceRegId=1;
    class RemindTask extends TimerTask 
    {
        @Override
        public void run() 
        {
            System.out.println("Triggering...!");
            onSendData();
            toolkit.beep();
        }
    }
    
    
    public FishValue() {
        initComponents();
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://master.herosite.pro:3306/aghosh_fish_ph", "aghosh", "farm2020");
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    void sendToServer()
    {
        
        try
        {
            float ph=Float.valueOf(txtPh.getText());
            PreparedStatement ps=con.prepareStatement("insert into sensor_value values(null,"+deviceRegId+",curdate(),"+Float.valueOf(txtPh.getText()+".0")+" ,'sam')");
            ps.execute();
            
            System.out.println("PH Sensor data inserted...");
            
            ps=null;
            ps=con.prepareStatement("select *  from  disease  where ph_value_min < "+ph+" AND ph_value_max > "+ph+" ");
          ResultSet rs=  ps.executeQuery();
          int diseaseId=0; 
          int f=0;
          String name="";
          if(rs.next())
            {
                f=1;
                diseaseId=rs.getInt(1);
                name=rs.getString(2);
            }
            rs.close();
            if(f==1)
            {
                ps=null;
                ps=con.prepareStatement("insert into problem_history values(null,"+deviceRegId+",curdate(),"+ph+","+diseaseId+" )");
                ps.execute();
                System.out.println("Disease detected...Disease name:"+name+" Id:"+diseaseId);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    java.util.Random r;  
    private void onSendData() {
		
        try 
                {
			// get input data for sending
			r=new Random();
                        int ph=r.nextInt(15);
                        txtPh.setText(""+ph);
                         txtPh.setText(ph+"");
                        
                        if(ph>8 )
                        {
                           
                            
                             jLabel1.setVisible(false);
                            
                            jLabel4.setVisible(true); 
                            
                        }
                        if(ph< 4)
                        {
                             jLabel1.setVisible(false);
                            
                            jLabel4.setVisible(true); 
                        
                        }
                        if(ph>= 4 && ph<= 8) 
                        {
                            jLabel1.setVisible(true);
                            
                            jLabel4.setVisible(false); 
                        }
                         
                         System.out.println("PH...!"+ph);
                        
                        System.out.println("in function...!");
			 
                        sendToServer();

		} catch (Exception ex) 
                {
			System.out.println(ex);
		}
	}
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPh = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swingserver/44.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 1000, 620);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swingserver/22.gif"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 30, 1180, 610);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 1320, 650);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("PH Value");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 40, 150, 60);

        txtPh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(txtPh);
        txtPh.setBounds(210, 50, 190, 40);

        jButton2.setText("Start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(1010, 60, 61, 25);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(1180, 60, 53, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Fish Farm Process");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(590, 60, 260, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 680, 1330, 130);

        setSize(new java.awt.Dimension(1382, 866));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        toolkit = Toolkit.getDefaultToolkit();
        timer = new Timer();
        timer.schedule(new RemindTask(), 4 * 1000,9 * 3000);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        sendToServer();
        // System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FishValue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FishValue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FishValue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FishValue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FishValue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtPh;
    // End of variables declaration//GEN-END:variables
}
